### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by bannik** [knacksteem/knacksteem-api#1]
So once the user got back from oath of steemconnect we should check if that user exists in our system, if yes log him in and retrieve all the data needed about him otherwise create a new user in our db and retrieve his info to the front end.

**Comment by bannik** [comment]
I am already recieving access token and getting redirected back on the frontend

**Comment by AneilPatel05** [comment]
@bannik    You need to use the Access Token and call the sc2 api ( sc2.me route returns user object).
This returned object needs to be sent to the back end via /login route. the API is ready for this operation.

**Comment by ateufel** [comment]
i´ve implemented the basic login including redirection to a user contribution page, will add a call to the login route soon.

**Comment by ateufel** [comment]
is a user check right after login even neccessary? after login you directly get to the "my contributions" page, where a call to the backend api should happen. in that call, you can check if the user already exists. no need for an extra call imho.

**Comment by jayserdny** [comment]
@onozasi @ms10398 Close this issue since it is no longer relevant.

@ateufel Contact me via chat
